
import { Challenge, ColorsConfig } from './types';

export const COLORS: ColorsConfig = {
  primary: 'bg-slate-900',
  secondary: 'bg-slate-800',
  accent: 'bg-amber-500',
  textPrimary: 'text-slate-100',
  textSecondary: 'text-slate-400',
  textAccent: 'text-amber-500',
  border: 'border-slate-700',
  buttonPrimary: 'bg-amber-500 hover:bg-amber-600',
  buttonSecondary: 'bg-slate-700 hover:bg-slate-600',
};

export const URL_IMAGE_HOME_SCREEN = 'https://fundacionleaencontexto.com/wp-content/uploads/2025/06/caminante.webp';

export const DESAFIOS: Challenge[] = [
  { 
    id: 1, 
    name: '01-Metáfora de vida', 
    apiKey: 'ROSA_DE_LOS_VIENTOS_001', 
    bookWord: 'corrales', 
    points: 10, 
    completed: false,
    questionPrompt: "Lee la página 0,000 N 0,004 W y encuentra el corazón de este proyecto; un proceso inherente a la vida misma",
    correctAnswer: "Caminar", 
    successMessage: "Ya abriste la puerta que te llevará a un mundo nuevo El sendero se despeja.",
    answerHintInBook: "Es un acto cotidiano que se realiza paso a paso.",
    bookWordLocationHint: "Esta palabra es el nombre de una vereda y la puedes encontrar en la página 0,000 N 0,002 W.",
    nextQrHint: "En la pantalla de inicio, puedes seguir el camino lineal o tomar el atajo que prefieras",
    qrCodeLocationHint: "El QR está escondido en algún lugar de la página 0,000 N 0,003 W",
    manualKeyHint: "La clave (ej. UNA_FRASE_PARECIDA_123) está escrita en la página 0,000 N 0,006 W."
  },
  { 
    id: 2, 
    name: '02-El mapa parlante', 
    apiKey: 'UN_CAMINO_POR_RECORRER_002', 
    bookWord: 'latitud', 
    points: 15, 
    completed: false,
    questionPrompt: "Es la evidencia tangible de un proceso pedagógico que respeta los ritmos naturales del apredizaje creativo; el resultado final del taller de Escritura creativa",
    correctAnswer: "el mapa parlante", 
    successMessage: "Ya estás en el territorio de los sentidos, el mapa te habla, el camino sigue.",
    answerHintInBook: "Esta es una invitación a confiar en los procesos, leyendo la página 1,111 N 1,016 W encontrarás la respuesta.",
    bookWordLocationHint: "La palabra clave es la coordenada del viaje que representa la imaginación infinita, según el texto de la página 1,111 N 1,009 W.",
    nextQrHint: "En la pantalla de inicio, puedes seguir el camino lineal o tomar el atajo que prefieras",
    qrCodeLocationHint: "Encontrarás el QR cerca de la rosa de los vientos, en la página 0,000 N 0,006 W",
    manualKeyHint: "La clave (ej. UNA_FRASE_PARECIDA_456) se encuentra cerca de la brújula de la introducción."
  },
  { 
    id: 3, 
    name: 'El Pico de la Lluvia de Estrellas', 
    apiKey: 'PEAK_KEY_EXAMPLE_789', 
    bookWord: 'cometa', 
    points: 20, 
    completed: false,
    questionPrompt: "En la cima del Pico de la Lluvia de Estrellas, ¿qué constelación debe alinearse para despertar al gigante dormido?",
    correctAnswer: "orión", 
    successMessage: "Las estrellas mismas se realinean, y la montaña tiembla mientras un poder ancestral se agita.",
    answerHintInBook: "Las cartas celestiales en el apéndice muestran la constelación del 'Descanso del Gigante'.",
    bookWordLocationHint: "Esta palabra se encuentra en la profecía grabada en el observatorio, sección de astronomía.",
    nextQrHint: "En la pantalla de inicio, puedes seguir el camino lineal o tomar el atajo que prefieras",
    qrCodeLocationHint: "El QR del Pico está en la página 42, al lado del poema sobre las estrellas fugaces.",
    manualKeyHint: "La clave (ej. PEAK_KEY_EXAMPLE_789) está impresa en vertical al margen de la página 42."
  },
  { 
    id: 4, 
    name: 'Las Cavernas Cristalinas', 
    apiKey: 'CAVES_KEY_GLIMMER_XYZ', 
    bookWord: 'cristal', 
    points: 25, 
    completed: false,
    questionPrompt: "En lo profundo de las Cavernas Cristalinas, ¿qué eco revela el sendero hacia la piedra corazón?",
    correctAnswer: "agua", 
    successMessage: "Los cristales vibran en armonía, y un pasaje oculto resplandece ante ti.",
    answerHintInBook: "Busca la respuesta en la descripción de la 'Cámara de los Ecos', capítulo 3.",
    bookWordLocationHint: "La palabra está oculta en el acertijo del guardián de la caverna, al final del capítulo 3.",
    nextQrHint: "En la pantalla de inicio, puedes seguir el camino lineal o tomar el atajo que prefieras",
    qrCodeLocationHint: "El QR de las Cavernas está oculto en la ilustración de la página 67, dentro de un cristal grande.",
    manualKeyHint: "Busca la clave (ej. CAVES_KEY_GLIMMER_XYZ) en la leyenda de la ilustración de la página 67."
  },
  { 
    id: 5, 
    name: 'La Ciudad de Engranajes', 
    apiKey: 'CITY_KEY_GEARS_ABC', 
    bookWord: 'autómata', 
    points: 30, 
    completed: false,
    questionPrompt: "En el corazón de la Ciudad de Engranajes, ¿qué rueda, al girar, da vida al Gran Planetario?",
    correctAnswer: "tiempo", 
    successMessage: "Con un clic satisfactorio, los engranajes de la ciudad giran, revelando una nueva maravilla de la ingeniería.",
    answerHintInBook: "El diagrama del 'Mecanismo Central' en el capítulo de inventos tiene la clave.",
    bookWordLocationHint: "Encuentra esta palabra en los planos del inventor, cerca del diagrama del Gran Reloj.",
    nextQrHint: "En la pantalla de inicio, puedes seguir el camino lineal o tomar el atajo que prefieras",
    qrCodeLocationHint: "Busca el QR de la Ciudad de Engranajes en el glosario, junto a la definición de 'Mecanismo'.",
    manualKeyHint: "La clave (ej. CITY_KEY_GEARS_ABC) está al final de la definición de 'Mecanismo' en el glosario."
  },
  { 
    id: 6, 
    name: 'El Paso de la Serpiente', 
    apiKey: 'PASS_KEY_SCALES_DEF', 
    bookWord: 'veneno', 
    points: 20, 
    completed: false,
    questionPrompt: "Para navegar con seguridad el Paso de la Serpiente, ¿qué ofrenda aplaca al antiguo guardián Coatl?",
    correctAnswer: "flor", 
    successMessage: "La gran serpiente inclina su cabeza escamada, otorgándote paso seguro a través de sus dominios.",
    answerHintInBook: "La leyenda del 'Guardián Escamado' menciona el tributo necesario. Revisa el bestiario.",
    bookWordLocationHint: "La palabra necesaria está tallada en el tótem que describe el ritual de paso seguro.",
    nextQrHint: "Busca el siguiente código en el altar de piedra al final del paso.",
    qrCodeLocationHint: "El QR del Paso de la Serpiente está en la página 99, al final del capítulo sobre bestias míticas.",
    manualKeyHint: "La clave (ej. PASS_KEY_SCALES_DEF) se encuentra en la nota al pie de la página 99."
  },
  { 
    id: 7, 
    name: 'El Telar del Tejedor de Sueños', 
    apiKey: 'LOOM_KEY_SILK_GHI', 
    bookWord: 'pesadilla', 
    points: 35, 
    completed: false,
    questionPrompt: "En el Telar del Tejedor de Sueños, ¿qué hebra, si se tira, puede desentrañar el miedo más profundo de un rey?",
    correctAnswer: "esperanza", 
    successMessage: "El telar resplandece, y los hilos del destino se realinean, concediéndote una visión del tapiz de los sueños.",
    answerHintInBook: "El capítulo sobre 'Magia Onírica' detalla los hilos y sus propiedades.",
    bookWordLocationHint: "Esta palabra se revela en el poema sobre el origen del telar, antes de la sección de patrones.",
    nextQrHint: "El próximo emblema se encuentra en la última página, en la dedicatoria del autor.",
    qrCodeLocationHint: "Encontrarás el QR del Telar en la sección de agradecimientos del libro, al final.",
    manualKeyHint: "La clave (ej. LOOM_KEY_SILK_GHI) está oculta en la primera letra de cada párrafo de la sección de agradecimientos."
  },
  { 
    id: 8, 
    name: 'El Santuario del Oráculo Silente', 
    apiKey: 'SHRINE_KEY_WHISPER_JKL', 
    bookWord: 'silencio', 
    points: 40, 
    completed: false,
    questionPrompt: "Ante el Santuario del Oráculo Silente, ¿qué verdad no dicha abre la última puerta de la sabiduría?",
    correctAnswer: "amor", 
    successMessage: "Un profundo entendimiento amanece, y la puerta final se abre, revelando la cúspide de tu búsqueda.",
    answerHintInBook: "La respuesta final no está escrita, sino que se deduce del prólogo y el epílogo combinados.",
    bookWordLocationHint: "La última palabra clave se insinúa en la meditación final del Oráculo, en el epílogo.",
    nextQrHint: null, 
    qrCodeLocationHint: "El QR final se encuentra en la solapa interior de la portada del libro. ¡Felicidades!",
    manualKeyHint: "La clave (ej. SHRINE_KEY_WHISPER_JKL) está en la solapa interior de la portada, debajo del QR final."
  },
];
